### ISSUE TITLE
[Bug] vite + vue3 + worker + wasm

### ISSUE THREAD

**Issue by Qwd2017** [cornerstonejs/cornerstone3D#1238]
### Describe the Bug

I want to convert labelmap segmentation to contour, but there is something wrong with @icr\polyseg-wasm.

### Steps to Reproduce

1.create a project with vite+vue3
2.install cornerstone3D  to project
3.copy and modify demo source code(https://www.cornerstonejs.org/live-examples/polysegwasmvolumelabelmaptocontour)  to project
4.run build

vite configuration is as follows:

import vue from "@vitejs/plugin-vue";
import wasm from "vite-plugin-wasm";

  return {
    plugins: [
      vue(),
      wasm(),
    ],
    worker: {
      plugins: [wasm()],
    },
  };

### The current behavior

throw new Error(`[vite]: Rollup failed to resolve import "${exporter}" from "${id}".\n` +
                          ^

Error: [vite]: Rollup failed to resolve import "a" from "xxx/node_modules/@icr/polyseg-wasm/dist/ICRPolySeg.wasm".
code: 'PLUGIN_ERROR',
plugin: 'commonjs--resolver',
hook: 'resolveId',
id: 'xxx/node_modules/@cornerstonejs/tools/dist/esm/stateManagement/segmentation/polySeg/registerPolySegWorker.js'

### The expected behavior

The project can be successfully built.

### OS

win10 20H2

### Node version

v18.16.0

### Browser

Chrome 124.0.6367.119

**Comment by shunia** [comment]
You are so lucky that I just fixed this and by accident I'm here seeing this issue, use `@rollup/plugin-wasm` instead:

```typescript
import { wasm } from "@rollup/plugin-wasm";

return {
  worker: {
    plugins: () => [wasm({ sync: ["ICRPolySeg.wasm"] })],
  },
  plugins: [wasm({ sync: ["ICRPolySeg.wasm"] })]
};
```

**Comment by Qwd2017** [comment]
@shunia Hi, thanks for your reply. I can make my project built with your guidance, but there is something error when I create and initialize ICRPolySeg object.
![2024-05-10_163347](https://github.com/cornerstonejs/cornerstone3D/assets/31121045/6137449b-2142-4dc2-837f-d986f5bda258)

**Comment by IrvingLu** [comment]
Hello, the OP is my colleague.
We have tried the plan you mentioned. This solution can compile successfully under vite5, but vite4 still fails. And I would like to ask, have you ever tried converting contour to labelmap under this framework? Have you tried this example https://www.cornerstonejs.org/live-examples/polysegwasmvolumelabelmaptocontour
I am unable to use this example correctly.
Also, I see that your address is Beijing. Can you leave a contact information? WeChat or email, we can discuss related issues together

**Comment by IrvingLu** [comment]
> Hello, the OP is my colleague. We have tried the plan you mentioned. This solution can compile successfully under vite5, but vite4 still fails. And I would like to ask, have you ever tried converting contour to labelmap under this framework? Have you tried this example https://www.cornerstonejs.org/live-examples/polysegwasmvolumelabelmaptocontour I am unable to use this example correctly. Also, I see that your address is Beijing. Can you leave a contact information? WeChat or email, we can discuss related issues together

When I use labelmap to convert to contour, the file under woker will become like this
![20240510-165023](https://github.com/cornerstonejs/cornerstone3D/assets/26640655/272e7c93-1028-4b8e-9675-47384a05caaf)

**Comment by sedghi** [comment]
I'm working on cornerstone3D 2.x and have made progress in removing circular dependencies and publishing the types for the DICOM image loader. I'm trying to make it work with Vite, but there are numerous issues with Vite in `dev` mode, which are not directly related to Cornerstone. Multiple mentions of Vite problems with `import.meta.url`, web workers, and WebAssembly can be found on the Vite GitHub repository:

https://github.com/vitejs/vite/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+import.meta.url

I have started a template project for Vite, React, and cornerstone3D beta 2.x here. I appreciate your help in making it work.

https://github.com/cornerstonejs/vite-react-cornerstone3d

**Comment by Qwd2017** [comment]
@sedghi Hi, I have tried a ugly method to resolve this problem since Vite does not support import wasm through import.meta.url. I uploaded a demo here https://github.com/Qwd2017/icrdemo.

**Comment by sedghi** [comment]
@Qwd2017 I can't see the config, https://github.com/Qwd2017/icrdemo/blob/main/icrdemo/vite.config.ts

Can you make sure the code is pushed?

**Comment by Qwd2017** [comment]
The file contents are as follows.

import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import { join } from "path";
import cp from "vite-plugin-cp";

function resolve(dir: string) {
  return join(__dirname, dir);
}

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    cp({
      hook: "buildStart",
      targets: [
        {
          src: "node_modules/@icr/polyseg-wasm/dist/ICRPolySeg.js",
          dest: "src/polyseg/",
        },
        {
          src: "node_modules/@icr/polyseg-wasm/dist/ICRPolySeg.wasm",
          dest: "./",
        },
        {
          src: "node_modules/@icr/polyseg-wasm/dist/ICRPolySeg.wasm",
          dest: "./public",
        },
      ],
    }),
  ],
  resolve: {
    alias: {
      "@cornerstonejs/tools": "@cornerstonejs/tools/dist/umd/index.js",
      "@": resolve("src"),
      "@cornerstonejs/dicom-image-loader":
        "@cornerstonejs/dicom-image-loader/dist/dynamic-import/cornerstoneDICOMImageLoader.min.js",
      "@icr/polyseg-wasm": resolve("src/polyseg/index.js"),
    },
  },
});

**Comment by kenny-reyes** [comment]
There is a workaround posted in the cornerstone Slack channel by **_Adrien_** that works for production:
Vite config add the following:

```
    plugins: [
      viteStaticCopy({
        targets: [
          {
            src: 'node_modules/@cornerstonejs/dicom-image-loader/dist/dynamic-import/*.wasm',
            dest: '.'
          },
          {
            src: 'node_modules/@cornerstonejs/dicom-image-loader/dist/dynamic-import/*.worker.js',
            dest: '.'
          }
        ]
      })
    ],

```
```
 resolve: {
      alias: [
        // Rollup can't bundle Cornerstone3D because of circular dependencies.
        // See https://github.com/cornerstonejs/cornerstone3D/issues/742
        ...(process.env.NODE_ENV === 'production'
          ? [
              {
                find: '@cornerstonejs/core',
                replacement: './node_modules/@cornerstonejs/core/dist/umd/index.js'
              },
              {
                find: '@cornerstonejs/tools',
                replacement: './node_modules/@cornerstonejs/tools/dist/umd/index.js'
              }
            ]
          : []),
        {
          // The worker bundling in the dicom loader is webpack specific, hack around it
          find: /^\/([^/]+).worker\.js(.map)?$/,
          replacement: './node_modules/@cornerstonejs/dicom-image-loader/dist/dynamic-import/$1.worker.js$2'
        },
        {
          find: '@',
          replacement: resolve('src/renderer/src')
        }
      ]
    },
```

Anyway this is a workaround and the bug should continue opened

**Comment by sedghi** [comment]
You can now safely use Cornerstone3D with WebAssembly and everything in Cornerstone3D 2.0. [See here.](https://www.cornerstonejs.org/docs/getting-started/vue-angular-react-etc/)
