### ISSUE TITLE
[Bug] Type error in polySeg initialisation

### ISSUE THREAD

**Issue by johnpage-agixis** [cornerstonejs/cornerstone3D#1880]
### Describe the Bug

The instructions for initialising tools with polySeg as described en the [README](https://github.com/cornerstonejs/cornerstone3D/tree/main/packages/polymorphic-segmentation) produces a type error.

NB. I have updated cornerstonejs/* to version 3.0.4

### Steps to Reproduce

Simple reproduction here: https://github.com/johnpage-agixis/polyseg-bug/blob/main/index.ts

Try to initialise tools with polySeg as described in the migration guide and in the README 
```ts
import { init } from '@cornerstonejs/tools';
import * as polySeg from '@cornerstonejs/polymorphic-segmentation';

// Initialize Cornerstone Tools with the Polymorphic Segmentation addon
await init({
  addons: {
    polySeg,
  },
});
```

### The current behavior

Type error
```
Type 'typeof import(".../node_modules/@cornerstonejs/polymorphic-segmentation/dist/esm/index")' is not assignable to type 'PolySegAddOn'.
  Types of property 'canComputeRequestedRepresentation' are incompatible.
    Type '(segmentationId: string, type: typeof SegmentationRepresentations) => boolean' is not assignable to type '(segmentationId: string, representationType: SegmentationRepresentations) => boolean'.
      Types of parameters 'type' and 'representationType' are incompatible.
        Type 'import(".../node_modules/@cornerstonejs/tools/dist/esm/enums/SegmentationRepresentations").default' is not assignable to type 'typeof SegmentationRepresentations'.ts(2322)
config.d.ts(21, 5): The expected type comes from property 'polySeg' which is declared here on type 'AddOns'
(property) polySeg: PolySegAddOn
```

### The expected behavior

No type error

### OS

Windows 10

### Node version

22.11.0

### Browser

N/A

**Comment by sedghi** [comment]
yeah we should fix the types

**Comment by mutex12** [comment]
Same issue with @cornerstonejs/polymorphic-segmentation updateSurfaceData(), return type is incorrect:

The types returned by 'updateSurfaceData(...)' are incompatible between these types.
  Type 'Promise<void>' is not assignable to type 'Promise<SurfaceSegmentationData>'.
    Type 'void' is not assignable to type 'SurfaceSegmentationData'.

**Comment by danieltabrizian** [comment]
Im still experiencing this issue in 3.10.30:
`TS2322: Type 'typeof import("/Users/daniel/IdeaProjects/PanoptesServer/panoptesV2/node_modules/@cornerstonejs/polymorphic-segmentation/dist/esm/index")' is not assignable to type 'PolySegAddOn'.
  The types returned by 'updateSurfaceData(...)' are incompatible between these types.
    Type 'Promise<void>' is not assignable to type 'Promise<SurfaceSegmentationData>'.
      Type 'void' is not assignable to type 'SurfaceSegmentationData'.
    40 |   await csRenderInit();
    41 |   // await csToolsInit();
  > 42 |   await csToolsInit({ addons: { polySeg } });`
